### ISSUE TITLE
[1pt] graph-prototype: Implement Callback Function to Notify Graph Owner of Full Node Setting Changes

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/gnuradio4#119]
We need to introduce a new feature: a callback function to alert the graph owner whenever a node's settings completely change. This feature will be significant for interfacing with UIs and other components that need to react to these changes.

### Expected Behaviour:

The callback should be triggered on any partial or full setting change and return the list of references to the nodes where the settings have changed. 
  * Partial changes are out of scope.
  * This process can be automated if a change is performed via the settings() interface and the callback registered after the `property_map` data is transferred to the block's struct fields.
  * In cases where users directly modify the block's struct fields, they may need to trigger the notify/change process manually.

### Proposed Implementation:
To facilitate this, we're considering an atomic counter or a condition variable for each node and graph. These components will serve a dual purpose:
  * A **blocking API**: users can block on them to get notified when a change occurs.
  * A **polling API** mechanism: users can poll the counter state, compare it with the old state, and deduce whether and how many changes have occurred. For example, if the return is 1, one block setting has changed; if it's >1, multiple settings have changed.
  
Using conditions variables should maintain acceptable performance, even with the use of mutexes, because settings changes are usually rare and not in the hot-path/processing thread. Any feedback or alternative suggestions are most welcome!

**Comment by RalphSteinhagen** [comment]
Has been completed with https://github.com/fair-acc/gnuradio4/pull/298
