### ISSUE TITLE
[2SP] GR: Implement a GR block that performs data chunking

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/gnuradio4#237]
The block should get the data as a continuous stream of type T,
and chunk/cut it between tags, or on custom defined points.
The chunks should be exported as DataSet<T>.

**Comment by RalphSteinhagen** [comment]
Intermediate result:

![Image](https://github.com/fair-acc/graph-prototype/assets/46007894/f2528369-9e25-4a4e-a3e3-f399cab34259)

pending: FAIR style filtering (requires runtime configurable expression evaluation), `DataSet<float>` export (needs Plugin system update)
