### ISSUE TITLE
[5SP;6SP] GR: Allow graph topology updates while running

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/gnuradio4#276]
We should introduce graph update requests into the messaging system - messages to request a new block to be added, a block to be replaced with another or removed.

It should also have messages for establishing port connections or disconnecting them.

**Comment by RalphSteinhagen** [comment]
Please consider that these messages should be communicated also via the service (GR<->Majordomo) and external client. 

*N.B. This does not include the corresponding UI components, handled in issue https://github.com/fair-acc/opendigitizer/issues/199 *

**Comment by ivan-cukic** [comment]
Related: https://github.com/fair-acc/gnuradio4/pull/448

**Comment by RalphSteinhagen** [comment]
finished by https://github.com/fair-acc/opendigitizer/pull/233
