### ISSUE TITLE
[3pt] graph-prototype: Consolidate UT-based tests and test applications

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/gnuradio4#97]
There is a lot of copy-paste code in the tests. Especially in the separate applications (`test/app_*.cpp`). The reason for the current test applications are issues with uT.

**Comment by RalphSteinhagen** [comment]
This is likely linked and/or could be combined with: https://github.com/fair-acc/opendigitizer/issues/91

@wirew0rm, what do you think?

**Comment by wirew0rm** [comment]
yes, I'm already working on that one :+1: for merging

**Comment by wirew0rm** [comment]
I think it's more related to #125 at least from the title?

Sounds like we have to either fix the issues with UT (mentioned issue) or add some light abstractions to reuse code between ut tests and test apps (this issue). The block refactoring tackles another kind of duplication? There is some overlap in in the files this touches, but conceptually the issues are different and #91 is simple refactoring while this one needs investigation and possibly fixes on the UT side, so I think it's easier to leave them separate for now. (Always possible to fix both in a single PR)

**Comment by RalphSteinhagen** [comment]
done.
